#!/bin/bash

SEC_FILE=$GITHUB_WORKSPACE/SECURITY.md
CON_FILE=$GITHUB_WORKSPACE/CONTRIBUTING.md
LIC_FILE=$GITHUB_WORKSPACE/LICENSE.md
COC_FILE=$GITHUB_WORKSPACE/CODE_OF_CONDUCT.md

PR_FILE=$GITHUB_WORKSPACE/.github/PULL_REQUEST_TEMPLATE.md

IT_FOLDER=$GITHUB_WORKSPACE/.github/ISSUE_TEMPLATE


cp $SEC_FILE .
cp $CON_FILE .
cp $LIC_FILE .
cp $COC_FILE .

cp $PR_FILE ./.github

cp $IT_FOLDER/* ./.github/ISSUE_TEMPLATE
